name: Check & Create PR

on:
  push:
    branches:
      - dev

permissions:
  contents: read 
  pull-requests: write  

jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      lenPrs: ${{ steps.check_pr.outputs.lenPrs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: check_pr
        name: Check PR list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
        run: |
          if [ "$ref" = "dev" ]; then
            lenPrs=$(gh pr list -B main -H dev --json id,title --jq '. | length')
            echo "lenPrs=$lenPrs" >> "$GITHUB_OUTPUT"
          else
            echo "not implemented yet"
          fi

  create-pr-main:
    needs: check_pr
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'dev' && needs.check_pr.outputs.lenPrs == 0 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR dev into main
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} 
        run: |
          reviewers=$(gh api "repos/${{ github.repository }}/collaborators?permission=admin" --jq '[.[] | .login] | join(",")')
          gh pr create -B main -H dev --title "Merge branch dev -> main - Auto Created" --body "Auto Created" --reviewer "$reviewers" --repo ${{ github.repository }} -t "Merge dev into main" -b "Automatic PR" -R ${{ github.repository }}