name: React.js CI

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
jobs:
  react_ci:
    name: Run React.js CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build React.js app
        run: npm build